### PR TITLE
updated EZFIO

### PR DESCRIPTION
**Pull request by kgasperich**

### CODE REVIEW

**Comment by TApplencourt** [comment]
Can you describe a little more kevin for Anthony to understand? :D

**Comment by kgasperich** [comment]
EZFIO was patched 2 months ago to fix an issue with string handling; I've updated the EZFIO tarball that is packaged with QP2.
https://gitlab.com/scemama/EZFIO/-/commit/e2a79a0c53af3916d9dedea36d9de86afe56511a

I'm not sure what the version number should be: it was changed to 2.0.2 five months ago (before the latest fix), so maybe it should be 2.0.3 now?
https://gitlab.com/scemama/EZFIO/-/commit/ec1956dc990cf34132d4bddfeab8818ce928b385

**Comment by kgasperich** [comment]
The earlier build failed because the top directory in the EZFIO.tar.gz downloaded from gitlab was `EZFIO-master/` (instead of `EZFIO/`)
I changed this to `EZFIO/` and uploaded again

**Comment by kgasperich** [comment]
There's still a problem with the ezfio, maybe in `get_conv` it should be
```
  conv = lambda x: x.decode('utf-8').strip() if isinstance(x,bytes) else x.strip()
```
https://gitlab.com/scemama/EZFIO/-/blob/master/src/ezfio-head.py#L105

**Comment by kgasperich** [comment]
I tried the fix described above on the `features_kpts` branch, and if the travis passes I'll add it here

**Comment by scemama** [comment]
I changed the configure to accept the tar.gz from gitlab to avoid the need of untaring and retaring the EZFIO. I made a push, so my last commit is more or less the same as this PR.
Thanks Kevin!

**Pull request closed without merging**
